CREATE TABLE ShoppingCartItems(
Id INT IDENTITY(1,1),
CartId UNIQUEIDENTIFIER NOT NULL ,
MenuItemId INT NOT NULL,
Name NVARCHAR(100) NOT NULL,
Price DECIMAL(18,2) NOT NULL,
Quantity INT NOT NULL,
CONSTRAINT PK_ShoppingCartItems PRIMARY KEY (Id),
CONSTRAINT FK_ShoppingCartItems_ShoppingCarts FOREIGN KEY (CartId) REFERENCES ShoppingCarts(Id) ON DELETE CASCADE);
