CREATE TABLE UserRoles(
UserId UNIQUEIDENTIFIER NOT NULL,
RoleId INT NOT NULL,
PRIMARY KEY (UserId,RoleId),
FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE,
FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE);