CREATE TABLE ShoppingCarts(
Id UNIQUEIDENTIFIER NOT NULL,
UserId UNIQUEIDENTIFIER NULL,
GuestId UNIQUEIDENTIFIER NULL,
CONSTRAINT PK_ShoppingCarts PRIMARY KEY (Id),
CONSTRAINT CHK_ShoppingCarts_Identity CHECK (UserId IS NOT NULL OR GuestId IS NOT NULL));