CREATE TABLE MenuItems(
Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(100) NOT NULL,
Description NVARCHAR(500) NULL,
Price DECIMAL(18,2) NOT NULL,
IsAvailable BIT NOT NULL DEFAULT 1
);

CREATE TABLE Users(
Id UNIQUEIDENTIFIER PRIMARY KEY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Email NVARCHAR(150) NOT NULL UNIQUE,
PasswordHash NVARCHAR(MAX) NOT NULL
);